from typing import List
from langchain_core.pydantic_v1 import BaseModel, Field, validator


class LangChainSchema(BaseModel):
    SystemMessage: str = Field(
        description="Describes the MAIN ROLE and behavior or action or the tone performed by the AI system"
    )
    HumanMessage: str = Field(
        description="Represents a message sent by a user seeking information, clarification, or engaging in conversation."
    )
    AssistantMessage: str = Field(
        description="Represents a response generated by the AI assistant in reply to a user's query or input."
    )

class ChatgptSchema(BaseModel):
    role: str = Field(description="Represents the role of the message sender, whether it's the system, the user, or the assistant.")
    content: str = Field(description="Represents the actual content of the message sent by the system, the user, or the assistant.")
