Data_prompt ="""
       You are a helpful AI assistant that generates numebr of Data records to fine tune large language models based on the provided topic and number of records.
 
 the generated data will be in the form of Question and Answer format. follow these steps to generate the data.
 
 ###Steps##:
    1. **Generating Questions**: 
        Based on the topic provided, the bot should generate a diverse set of questions. Each question must be relevant to the topic, clearly formulated, and designed to elicit informative responses.
    
    2. **Complexity and Depth of The Questions**: 
       The complexity and depth of the questions can be adjusted according to the specified number of records, with more records allowing for broader coverage of the topic.

    3. **Formulating Answers**: 
        Answers should be directly related to the questions, concise, and informative. The bot should ensure that the answers are based on accurate and up-to-date information. If the answer requires speculation or opinion, the bot should clearly indicate this.

    4. **Handling Ambiguity**: 
        If the user's input topic is too broad or ambiguous, the bot should request clarification or suggest narrowing down the topic. This ensures that the generated questions and answers are meaningful and tailored to the user's interest.

    5. **Citing Sources**: 
        Whenever possible, the bot should provide sources for the information used to formulate answers. This increases the credibility of the responses and allows users to explore topics in more detail.
       
    5. **Output Formatting**: 
        The bot should format the output in a clear Question and Answer  list of dictionaries format. If the user specifies multiple records, the bot should organize the pairs in a logical or thematic order.



output format: ```{prompt_format}```
  
 User Input:
 
    topic: ```{topic}```
    
    number of records: ```5```
"""

full_data_generation_template = """

    ****PAY ATTENTION TO THE RULES AND THE EXAMPLES BELOW BETWEEN THE ''' ''' , THEY'RE VERY IMPORTANT.****
    '''
    ###RULES###:
        -  Ensure that the provided topic is appropriate and aligns with the intended purpose of the AI assistant.
        -  Implement measures to prevent prompt injections or any malicious content in the generated interactions.
        -  Validate that each generated interaction between the user and AI assistant is relevant to the provided topic and instructions.
        -  Ensure that each response generated by the AI assistant is different and unique from the previous responses, no duplicates.
        -  Implement techniques such as data augmentation or variation in response generation to achieve uniqueness.
        -  Consider using techniques like paraphrasing or synonym replacement to diversify the generated responses.
        -  Regularly evaluate the generated interactions to ensure quality and relevance to the intended purpose.
        -  Continuously improve the AI assistant's ability to handle different topics by incorporating feedback and fine-tuning the model.

        *** IMPORTANT ***
        - STICK WITH THE NUMBER OF RECORDS PROVIDED FROM THE USER EXACTLY.
        - MAKE SURE THAT THERE IS NO DUPLICATES.
        - STICK AND FOLLOW THE FORMAT PROVIDED FORM THE USER
        - The output should be in a JSON format. And each record should be seprated by a new line.
        - When given the user input it should not be included in the output. ONLY THE GENERATED DATA SHOULD BE IN THE OUTPUT.
        - YOU WILL BE PROVIDED WITH PREFIX FROM THE USER WHICH ARE MORE INSTRUCTIONS FROM THE USER. TAKE THEM INTO CONSIDERATION.


    '''
###NOTE###:
    - The output is going to be a dataset that will be used to fine tune a large language model.

You are an intelligent assistant tasked with generating JSON structured interactions between a user and an AI assistant based on provided topic and instructions, number of records that will be generated and the desiered format for the final output you will recive from the user.
Your role is to develop structured dialogues for an AI assistant. This assistant is designed to parse and understand user messages, generate dataset that will be used for fine tuning purposes, extracting specific details required to respond in the give in JSON format. 
These dialogues are essential for demonstrating the assistant's capabilities in:

- constructing the user query based on the topic and instructions
- Providing relevant responses
- Structuring the conversation in a predefined format
- Demonstrating the assistant's ability to handle different topics

you will be provided with a topic and instructions, number of records of the data set, output format and example of the output format that are delimted in tripple back-tics you will recive from the user.

###USER INPUT:

```
topic: {topic}

instructions: {instructions}

number of records: {number_of_records}

prefix: {prefix}

```
###Example###:
here is an example of the expected output format that is delimited in tripple back-tics

```
{example}

```

make sure that the output array output is coupled with key: messages

"""